spring.application.name=demo
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.datasource.url=jdbc:mysql://localhost:3306/aulafrank
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true