spring.datasource.password=
# para criar a senha vai no gerenciador da conta do emal -> senha de app e cria um novo
spring.mail.password=wkei cfrx pzgx htns
jwt.secret=string_de_pelo_menos_32_caracteres
jwt.expiration=1000000